# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'icenine/ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Icenine(object):
    def setupUi(self, Icenine):
        Icenine.setObjectName("Icenine")
        Icenine.resize(826, 774)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(Icenine.sizePolicy().hasHeightForWidth())
        Icenine.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/images/icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Icenine.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Icenine)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(400, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mainLayout = QtWidgets.QHBoxLayout()
        self.mainLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.mainLayout.setSpacing(5)
        self.mainLayout.setObjectName("mainLayout")
        self.accountListView = QtWidgets.QListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accountListView.sizePolicy().hasHeightForWidth())
        self.accountListView.setSizePolicy(sizePolicy)
        self.accountListView.setMinimumSize(QtCore.QSize(250, 400))
        self.accountListView.setObjectName("accountListView")
        self.mainLayout.addWidget(self.accountListView)
        spacerItem = QtWidgets.QSpacerItem(13, 500, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.mainLayout.addItem(spacerItem)
        self.createTransactionBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createTransactionBox.sizePolicy().hasHeightForWidth())
        self.createTransactionBox.setSizePolicy(sizePolicy)
        self.createTransactionBox.setMinimumSize(QtCore.QSize(400, 400))
        self.createTransactionBox.setObjectName("createTransactionBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.createTransactionBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fromLabel = QtWidgets.QLabel(self.createTransactionBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fromLabel.sizePolicy().hasHeightForWidth())
        self.fromLabel.setSizePolicy(sizePolicy)
        self.fromLabel.setObjectName("fromLabel")
        self.verticalLayout.addWidget(self.fromLabel)
        self.fromAccount = QtWidgets.QLineEdit(self.createTransactionBox)
        self.fromAccount.setMaxLength(66)
        self.fromAccount.setReadOnly(True)
        self.fromAccount.setObjectName("fromAccount")
        self.verticalLayout.addWidget(self.fromAccount)
        self.toLabel = QtWidgets.QLabel(self.createTransactionBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toLabel.sizePolicy().hasHeightForWidth())
        self.toLabel.setSizePolicy(sizePolicy)
        self.toLabel.setObjectName("toLabel")
        self.verticalLayout.addWidget(self.toLabel)
        self.to = QtWidgets.QLineEdit(self.createTransactionBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to.sizePolicy().hasHeightForWidth())
        self.to.setSizePolicy(sizePolicy)
        self.to.setMinimumSize(QtCore.QSize(200, 0))
        self.to.setMaxLength(66)
        self.to.setFrame(True)
        self.to.setObjectName("to")
        self.verticalLayout.addWidget(self.to)
        self.amountLabel = QtWidgets.QLabel(self.createTransactionBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amountLabel.sizePolicy().hasHeightForWidth())
        self.amountLabel.setSizePolicy(sizePolicy)
        self.amountLabel.setObjectName("amountLabel")
        self.verticalLayout.addWidget(self.amountLabel)
        self.amount = QtWidgets.QLineEdit(self.createTransactionBox)
        self.amount.setObjectName("amount")
        self.verticalLayout.addWidget(self.amount)
        self.gasLimitLabel = QtWidgets.QLabel(self.createTransactionBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gasLimitLabel.sizePolicy().hasHeightForWidth())
        self.gasLimitLabel.setSizePolicy(sizePolicy)
        self.gasLimitLabel.setObjectName("gasLimitLabel")
        self.verticalLayout.addWidget(self.gasLimitLabel)
        self.gasLimit = QtWidgets.QLineEdit(self.createTransactionBox)
        self.gasLimit.setObjectName("gasLimit")
        self.verticalLayout.addWidget(self.gasLimit)
        self.gasPriceLabel = QtWidgets.QLabel(self.createTransactionBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gasPriceLabel.sizePolicy().hasHeightForWidth())
        self.gasPriceLabel.setSizePolicy(sizePolicy)
        self.gasPriceLabel.setObjectName("gasPriceLabel")
        self.verticalLayout.addWidget(self.gasPriceLabel)
        self.gasPrice = QtWidgets.QSpinBox(self.createTransactionBox)
        self.gasPrice.setMinimum(1)
        self.gasPrice.setProperty("value", 20)
        self.gasPrice.setObjectName("gasPrice")
        self.verticalLayout.addWidget(self.gasPrice)
        self.nonceLabel = QtWidgets.QLabel(self.createTransactionBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nonceLabel.sizePolicy().hasHeightForWidth())
        self.nonceLabel.setSizePolicy(sizePolicy)
        self.nonceLabel.setObjectName("nonceLabel")
        self.verticalLayout.addWidget(self.nonceLabel)
        self.nonce = QtWidgets.QLineEdit(self.createTransactionBox)
        self.nonce.setObjectName("nonce")
        self.verticalLayout.addWidget(self.nonce)
        self.label_7 = QtWidgets.QLabel(self.createTransactionBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.data = QtWidgets.QTextEdit(self.createTransactionBox)
        self.data.setObjectName("data")
        self.verticalLayout.addWidget(self.data)
        self.createTransactionButton = QtWidgets.QPushButton(self.createTransactionBox)
        self.createTransactionButton.setObjectName("createTransactionButton")
        self.verticalLayout.addWidget(self.createTransactionButton)
        self.mainLayout.addWidget(self.createTransactionBox)
        self.mainLayout.setStretch(0, 200)
        self.mainLayout.setStretch(1, 1)
        self.gridLayout.addLayout(self.mainLayout, 0, 0, 1, 1)
        Icenine.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Icenine)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAliases = QtWidgets.QMenu(self.menubar)
        self.menuAliases.setObjectName("menuAliases")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTransactions = QtWidgets.QMenu(self.menubar)
        self.menuTransactions.setObjectName("menuTransactions")
        Icenine.setMenuBar(self.menubar)
        self.actionOpen_Keystore_File = QtWidgets.QAction(Icenine)
        self.actionOpen_Keystore_File.setObjectName("actionOpen_Keystore_File")
        self.actionImportFromSeed = QtWidgets.QAction(Icenine)
        self.actionImportFromSeed.setObjectName("actionImportFromSeed")
        self.actionSave_All_Accounts = QtWidgets.QAction(Icenine)
        self.actionSave_All_Accounts.setObjectName("actionSave_All_Accounts")
        self.actionAdd_Alias = QtWidgets.QAction(Icenine)
        self.actionAdd_Alias.setObjectName("actionAdd_Alias")
        self.actionView_Aliases = QtWidgets.QAction(Icenine)
        self.actionView_Aliases.setObjectName("actionView_Aliases")
        self.actionImport_Aliases = QtWidgets.QAction(Icenine)
        self.actionImport_Aliases.setObjectName("actionImport_Aliases")
        self.actionExport_Aliases = QtWidgets.QAction(Icenine)
        self.actionExport_Aliases.setObjectName("actionExport_Aliases")
        self.actionAbout_Icenine = QtWidgets.QAction(Icenine)
        self.actionAbout_Icenine.setObjectName("actionAbout_Icenine")
        self.actionNew_Account = QtWidgets.QAction(Icenine)
        self.actionNew_Account.setObjectName("actionNew_Account")
        self.actionView_Transactions = QtWidgets.QAction(Icenine)
        self.actionView_Transactions.setObjectName("actionView_Transactions")
        self.menuFile.addAction(self.actionOpen_Keystore_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionNew_Account)
        self.menuFile.addAction(self.actionImportFromSeed)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_All_Accounts)
        self.menuAliases.addAction(self.actionView_Aliases)
        self.menuAliases.addSeparator()
        self.menuAliases.addAction(self.actionImport_Aliases)
        self.menuAliases.addAction(self.actionExport_Aliases)
        self.menuHelp.addAction(self.actionAbout_Icenine)
        self.menuTransactions.addAction(self.actionView_Transactions)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAliases.menuAction())
        self.menubar.addAction(self.menuTransactions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Icenine)
        QtCore.QMetaObject.connectSlotsByName(Icenine)

    def retranslateUi(self, Icenine):
        _translate = QtCore.QCoreApplication.translate
        Icenine.setWindowTitle(_translate("Icenine", "Icenine"))
        self.createTransactionBox.setTitle(_translate("Icenine", "Create Transaction"))
        self.fromLabel.setText(_translate("Icenine", "From"))
        self.toLabel.setText(_translate("Icenine", "To"))
        self.amountLabel.setText(_translate("Icenine", "Amount Ξ"))
        self.gasLimitLabel.setText(_translate("Icenine", "Gas Limit"))
        self.gasLimit.setText(_translate("Icenine", " 21000"))
        self.gasPriceLabel.setText(_translate("Icenine", "Gas Price (gwei)"))
        self.nonceLabel.setText(_translate("Icenine", "Nonce"))
        self.label_7.setText(_translate("Icenine", "Data"))
        self.data.setPlaceholderText(_translate("Icenine", "0x0"))
        self.createTransactionButton.setText(_translate("Icenine", "Create Transaction"))
        self.menuFile.setTitle(_translate("Icenine", "File"))
        self.menuAliases.setTitle(_translate("Icenine", "Aliases"))
        self.menuHelp.setTitle(_translate("Icenine", "Help"))
        self.menuTransactions.setTitle(_translate("Icenine", "Transactions"))
        self.actionOpen_Keystore_File.setText(_translate("Icenine", "Open Keystore"))
        self.actionOpen_Keystore_File.setShortcut(_translate("Icenine", "Ctrl+O"))
        self.actionImportFromSeed.setText(_translate("Icenine", "Import From Seed"))
        self.actionImportFromSeed.setShortcut(_translate("Icenine", "Ctrl+B"))
        self.actionSave_All_Accounts.setText(_translate("Icenine", "Save All Accounts"))
        self.actionSave_All_Accounts.setShortcut(_translate("Icenine", "Ctrl+S"))
        self.actionAdd_Alias.setText(_translate("Icenine", "Add Alias"))
        self.actionAdd_Alias.setShortcut(_translate("Icenine", "Alt+A"))
        self.actionView_Aliases.setText(_translate("Icenine", "View/Edit Aliases"))
        self.actionView_Aliases.setShortcut(_translate("Icenine", "Alt+C"))
        self.actionImport_Aliases.setText(_translate("Icenine", "Import Aliases"))
        self.actionExport_Aliases.setText(_translate("Icenine", "Export Aliases"))
        self.actionAbout_Icenine.setText(_translate("Icenine", "About Icenine"))
        self.actionNew_Account.setText(_translate("Icenine", "New Account"))
        self.actionView_Transactions.setText(_translate("Icenine", "View Transactions"))

from icenine.ui import assets_rc
