# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'icenine/ui/newaccountdialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_newAccountDialog(object):
    def setupUi(self, newAccountDialog):
        newAccountDialog.setObjectName("newAccountDialog")
        newAccountDialog.resize(882, 478)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/images/icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        newAccountDialog.setWindowIcon(icon)
        self.buttonBox = QtWidgets.QDialogButtonBox(newAccountDialog)
        self.buttonBox.setGeometry(QtCore.QRect(530, 450, 341, 21))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.createAccountTabs = QtWidgets.QTabWidget(newAccountDialog)
        self.createAccountTabs.setGeometry(QtCore.QRect(0, 50, 881, 391))
        self.createAccountTabs.setObjectName("createAccountTabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.privateKeyRandom = QtWidgets.QTextEdit(self.tab)
        self.privateKeyRandom.setGeometry(QtCore.QRect(10, 130, 861, 111))
        self.privateKeyRandom.setObjectName("privateKeyRandom")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 91, 17))
        self.label_2.setObjectName("label_2")
        self.generateRandomButton = QtWidgets.QPushButton(self.tab)
        self.generateRandomButton.setGeometry(QtCore.QRect(250, 40, 391, 25))
        self.generateRandomButton.setObjectName("generateRandomButton")
        self.addressRandom = QtWidgets.QLineEdit(self.tab)
        self.addressRandom.setGeometry(QtCore.QRect(10, 280, 861, 25))
        self.addressRandom.setObjectName("addressRandom")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 260, 67, 17))
        self.label_3.setObjectName("label_3")
        self.createAccountTabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.seedWords = QtWidgets.QTextEdit(self.tab_2)
        self.seedWords.setGeometry(QtCore.QRect(10, 30, 861, 70))
        self.seedWords.setObjectName("seedWords")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 81, 17))
        self.label_4.setObjectName("label_4")
        self.generateWordsButton = QtWidgets.QPushButton(self.tab_2)
        self.generateWordsButton.setGeometry(QtCore.QRect(10, 110, 421, 25))
        self.generateWordsButton.setObjectName("generateWordsButton")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 91, 17))
        self.label_5.setObjectName("label_5")
        self.privateKeySeed = QtWidgets.QTextEdit(self.tab_2)
        self.privateKeySeed.setGeometry(QtCore.QRect(10, 170, 861, 111))
        self.privateKeySeed.setObjectName("privateKeySeed")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(10, 300, 67, 17))
        self.label_6.setObjectName("label_6")
        self.addressSeed = QtWidgets.QLineEdit(self.tab_2)
        self.addressSeed.setGeometry(QtCore.QRect(10, 320, 861, 25))
        self.addressSeed.setObjectName("addressSeed")
        self.loadWordsButton = QtWidgets.QPushButton(self.tab_2)
        self.loadWordsButton.setGeometry(QtCore.QRect(450, 110, 421, 25))
        self.loadWordsButton.setObjectName("loadWordsButton")
        self.createAccountTabs.addTab(self.tab_2, "")
        self.label = QtWidgets.QLabel(newAccountDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 861, 41))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.accountGenerationProgress = QtWidgets.QProgressBar(newAccountDialog)
        self.accountGenerationProgress.setGeometry(QtCore.QRect(0, 450, 691, 23))
        self.accountGenerationProgress.setProperty("value", 0)
        self.accountGenerationProgress.setTextVisible(False)
        self.accountGenerationProgress.setObjectName("accountGenerationProgress")

        self.retranslateUi(newAccountDialog)
        self.createAccountTabs.setCurrentIndex(1)
        self.buttonBox.accepted.connect(newAccountDialog.accept)
        self.buttonBox.rejected.connect(newAccountDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(newAccountDialog)

    def retranslateUi(self, newAccountDialog):
        _translate = QtCore.QCoreApplication.translate
        newAccountDialog.setWindowTitle(_translate("newAccountDialog", "New Account"))
        self.label_2.setText(_translate("newAccountDialog", "Private Key"))
        self.generateRandomButton.setText(_translate("newAccountDialog", "Generate New Account"))
        self.label_3.setText(_translate("newAccountDialog", "Address"))
        self.createAccountTabs.setTabText(self.createAccountTabs.indexOf(self.tab), _translate("newAccountDialog", "Random Seed"))
        self.label_4.setText(_translate("newAccountDialog", "Seed Words"))
        self.generateWordsButton.setText(_translate("newAccountDialog", "Generate New Words"))
        self.label_5.setText(_translate("newAccountDialog", "Private Key"))
        self.label_6.setText(_translate("newAccountDialog", "Address"))
        self.loadWordsButton.setText(_translate("newAccountDialog", "Load From Words"))
        self.createAccountTabs.setTabText(self.createAccountTabs.indexOf(self.tab_2), _translate("newAccountDialog", "Seed Words"))
        self.label.setText(_translate("newAccountDialog", "You can create a new account using a completely random seed, or generate(or import) an account using random seed words.  Random is more secure, but you will not be able to recreate the account using seed words if you lose your private key."))

from icenine.ui import assets_rc
